file = open('ex1.py')
all_lines = file.readlines()
print(all_lines[4])
print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
#print("I said don't touch this.")
print("We running shit now!")
